import { type Serie } from "./types.tsx";
import { type SeasonSerie } from "./types.tsx";

export const series: Serie[] = [
  {
    id: 1,
    type: "serie",
    title: "Breaking Bad",
    poster: "/Breaking Bad (2008).jpeg",
    // poster: "/series/breaking_bad/Breaking Bad (2008).jpg",
    color: "rgba(244, 189, 28, 0.8)",
    background:
      "https://image.tmdb.org/t/p/original/cFXxKJzGrvjcmMJAReNekx0RVJb.jpg",
    // "https://image.tmdb.org/t/p/original/lKODbE8ARPJEPnjTBfiIJ98I3YL.jpg",
    // "",
    seasons: 5,
    episodes: 62,
    creator: "Vince Gilligan",
    synopsis:
      "Un profesor de química se convierte en narcotraficante de metanfetaminas.",
    seasons_data: [
      {
        id_serie: 1,
        season_number: 1,
        year: 2008,
        poster: "/series/breaking_bad/Breaking Bad (2008) - Season 1.jpg",
        color: "rgba(62, 111, 140, 1)",
        episodes: [
          { number: 1, progress: 100 },
          { number: 2, progress: 100 },
          { number: 3, progress: 100 },
          { number: 4, progress: 100 },
          { number: 5, progress: 100 },
          { number: 6, progress: 100 },
          { number: 7, progress: 100 },
        ],
      },
      {
        id_serie: 1,
        season_number: 2,
        year: 2009,
        poster: "/series/breaking_bad/Breaking Bad (2008) - Season 2.jpg",
        color: "rgba(180, 180, 170, 1)",
        episodes: [
          { number: 1, progress: 100 },
          { number: 2, progress: 100 },
          { number: 3, progress: 100 },
          { number: 4, progress: 100 },
          { number: 5, progress: 100 },
          { number: 6, progress: 100 },
          { number: 7, progress: 100 },
          { number: 8, progress: 100 },
          { number: 9, progress: 100 },
          { number: 10, progress: 100 },
          { number: 11, progress: 100 },
          { number: 12, progress: 100 },
          { number: 13, progress: 100 },
        ],
      },
      {
        id_serie: 1,
        season_number: 3,
        year: 2010,
        poster: "/series/breaking_bad/Breaking Bad (2008) - Season 3.jpg",
        color: "rgba(193, 128, 38, 1)",
        episodes: [
          { number: 1, progress: 100 },
          { number: 2, progress: 100 },
          { number: 3, progress: 100 },
          { number: 4, progress: 100 },
          { number: 5, progress: 100 },
          { number: 6, progress: 100 },
          { number: 7, progress: 100 },
          { number: 8, progress: 100 },
          { number: 9, progress: 100 },
          { number: 10, progress: 100 },
          { number: 11, progress: 100 },
          { number: 12, progress: 100 },
          { number: 13, progress: 100 },
        ],
      },
      {
        id_serie: 1,
        season_number: 4,
        year: 2011,
        poster: "/series/breaking_bad/Breaking Bad (2008) - Season 4.jpg",
        color: "rgba(160, 66, 64, 1)",
        episodes: [
          { number: 1, progress: 100 },
          { number: 2, progress: 100 },
          { number: 3, progress: 100 },
          { number: 4, progress: 100 },
          { number: 5, progress: 100 },
          { number: 6, progress: 100 },
          { number: 7, progress: 100 },
          { number: 8, progress: 100 },
          { number: 9, progress: 100 },
          { number: 10, progress: 100 },
          { number: 11, progress: 100 },
          { number: 12, progress: 100 },
          { number: 13, progress: 100 },
        ],
      },
      {
        id_serie: 1,
        season_number: 5,
        year: 2012,
        poster: "/series/breaking_bad/Breaking Bad (2008) - Season 5.jpg",
        color: "rgba(103, 75, 50, 1)",
        episodes: [
          { number: 1, progress: 100 },
          { number: 2, progress: 100 },
          { number: 3, progress: 100 },
          { number: 4, progress: 100 },
          { number: 5, progress: 100 },
          { number: 6, progress: 100 },
          { number: 7, progress: 100 },
          { number: 8, progress: 100 },
          { number: 9, progress: 100 },
          { number: 10, progress: 100 },
          { number: 11, progress: 100 },
          { number: 12, progress: 100 },
          { number: 13, progress: 100 },
          { number: 14, progress: 100 },
          { number: 15, progress: 100 },
          { number: 16, progress: 100 },
        ],
      },
    ],
  },
  {
    id: 2,
    type: "serie",
    title: "Dark",
    poster: "/series/Dark/Dark (2017) (3).png",
    color: "rgba(88, 88, 88, 0.8)",
    background:
      "https://image.tmdb.org/t/p/original/5WtjkKOzRTyt3AH8KgIGavO2CQu.jpg",
    seasons: 3,
    episodes: 26,
    creator: "Baran bo Odar, Jantje Friese",
    synopsis:
      "En la ciudad de Winden comienzan a desaparecer niños, sacando a la luz las relaciones fracturadas, vidas dobles y el pasado oscuro de cuatro familias (Kahnwald, Nielsen, Tiedemann y Doppler) que viven allí, y revelando un misterio que abarca cuatro generaciones.",
    seasons_data: [
      {
        id_serie: 2,
        season_number: 1,
        year: 2017,
        poster: "/series/Dark/Dark (2017) - Season 1.png",
        color: "rgba(61, 104, 117, 1)",
        episodes: [
          { number: 1, progress: 100 },
          { number: 2, progress: 100 },
          { number: 3, progress: 100 },
          { number: 4, progress: 100 },
          { number: 5, progress: 100 },
          { number: 6, progress: 100 },
          { number: 7, progress: 100 },
          { number: 8, progress: 100 },
          { number: 9, progress: 100 },
          { number: 10, progress: 100 },
        ],
      },
      {
        id_serie: 2,
        season_number: 2,
        year: 2019,
        poster: "/series/Dark/Dark (2017) - Season 2.png",
        color: "rgba(136, 117, 84, 1)",
        episodes: [
          { number: 1, progress: 100 },
          { number: 2, progress: 100 },
          { number: 3, progress: 100 },
          { number: 4, progress: 100 },
          { number: 5, progress: 100 },
          { number: 6, progress: 100 },
          { number: 7, progress: 100 },
          { number: 8, progress: 100 },
        ],
      },
      {
        id_serie: 2,
        season_number: 3,
        year: 2020,
        poster: "/series/Dark/Dark (2017) - Season 3.png",
        color: "rgba(218, 174, 123, 1)",
        episodes: [
          { number: 1, progress: 100 },
          { number: 2, progress: 100 },
          { number: 3, progress: 100 },
          { number: 4, progress: 100 },
          { number: 5, progress: 100 },
          { number: 6, progress: 100 },
          { number: 7, progress: 100 },
          { number: 8, progress: 100 },
        ],
      },
    ],
  },
  {
    id: 3,
    type: "serie",
    title: "Daredevil",
    genre: "superheroes",
    poster:
      "https://image.tmdb.org/t/p/original/5ND7iEoiDEaKBdE6ol5f9ovAM9v.jpg",
    color: "rgba(193, 20, 20, 0.8)",
    background:
      "https://image.tmdb.org/t/p/original/AbQoohUsJLlVpbctoAQ2BsZtPIc.jpg",
    // "https://image.tmdb.org/t/p/original/3JTheOV0ri8xkf2TWOpMupQeT4I.jpg",
    seasons: 3,
    episodes: 39,
    creator: "Steven S. DeKnight",
    synopsis:
      "Un abogado ciego lucha contra el crimen en Hell's Kitchen, Nueva York, como vigilante por la noche.",
    seasons_data: [
      {
        id_serie: 3,
        season_number: 1,
        year: 2015,
        poster: "/series/Daredevil/Daredevil (2015) - Season 1.png",
        color: "rgba(38, 74, 126, 1)",
        episodes: [
          { number: 1, progress: 100 },
          { number: 2, progress: 100 },
          { number: 3, progress: 100 },
          { number: 4, progress: 100 },
          { number: 5, progress: 100 },
          { number: 6, progress: 100 },
          { number: 7, progress: 100 },
          { number: 8, progress: 100 },
          { number: 9, progress: 100 },
          { number: 10, progress: 100 },
          { number: 11, progress: 100 },
          { number: 12, progress: 100 },
          { number: 13, progress: 100 },
        ],
      },
      {
        id_serie: 3,
        season_number: 2,
        year: 2016,
        poster: "/series/Daredevil/Daredevil (2015) - Season 2.png",
        color: "rgba(94, 94, 94, 1)",
        episodes: [
          { number: 1, progress: 100 },
          { number: 2, progress: 100 },
          { number: 3, progress: 100 },
          { number: 4, progress: 100 },
          { number: 5, progress: 100 },
          { number: 6, progress: 100 },
          { number: 7, progress: 100 },
          { number: 8, progress: 100 },
          { number: 9, progress: 100 },
          { number: 10, progress: 100 },
          { number: 11, progress: 100 },
          { number: 12, progress: 100 },
          { number: 13, progress: 100 },
        ],
      },
      {
        id_serie: 3,
        season_number: 3,
        year: 2018,
        poster: "/series/Daredevil/Daredevil (2015) - Season 3.png",
        color: "rgba(0, 0, 0, 1)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
          { number: 11, progress: 0 },
          { number: 12, progress: 0 },
          { number: 13, progress: 0 },
        ],
      },
    ],
  },
  {
    id: 4,
    type: "serie",
    title: "Better Call Saul",
    poster: "/series/better_call_saul/Better Call Saul (2015).jpg",
    color: "rgba(249, 223, 149, 0.8)",
    background:
      "https://image.tmdb.org/t/p/original/egcNHq9PQDprPPTDlF3rys6WVy.jpg",
    seasons: 6,
    episodes: 63,
    creator: "Vince Gilligan, Peter Gould",
    synopsis:
      "La historia de cómo Jimmy McGill se convierte en el abogado criminal Saul Goodman.",
    seasons_data: [
      {
        id_serie: 4,
        season_number: 1,
        year: 2015,
        poster:
          "/series/better_call_saul/Better Call Saul (2015) - Season 1.png",
        color: "rgba(96, 127, 159, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
        ],
      },
      {
        id_serie: 4,
        season_number: 2,
        year: 2016,
        poster:
          "/series/better_call_saul/Better Call Saul (2015) - Season 2.png",
        color: "rgba(129, 129, 125, 1)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
        ],
      },
      {
        id_serie: 4,
        season_number: 3,
        year: 2017,
        poster:
          "/series/better_call_saul/Better Call Saul (2015) - Season 3.png",
        color: "rgba(42, 58, 96, 1)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
        ],
      },
      {
        id_serie: 4,
        season_number: 4,
        year: 2020,
        poster:
          "/series/better_call_saul/Better Call Saul (2015) - Season 4.png",
        color: "rgba(107, 107, 107, 1)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
        ],
      },
      {
        id_serie: 4,
        season_number: 5,
        year: 2020,
        poster:
          "/series/better_call_saul/Better Call Saul (2015) - Season 5.png",
        color: "rgba(231, 231, 231, 1)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
        ],
      },
      {
        id_serie: 4,
        season_number: 6,
        year: 2022,
        poster:
          "/series/better_call_saul/Better Call Saul (2015) - Season 6.png",
        color: "rgba(0, 0, 0, 1)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
          { number: 11, progress: 0 },
          { number: 12, progress: 0 },
          { number: 13, progress: 0 },
        ],
      },
    ],
  },
  {
    id: 5,
    type: "serie",
    title: "Invincible",
    group: "animation",
    genre: "superheroes",
    poster:
      // "https://image.tmdb.org/t/p/original/dMOpdkrDC5dQxqNydgKxXjBKyAc.jpg",
      "/series/invincible/INVINCIBLE (2021).jpg",
    // color: "rgba(147, 56, 35, 0.8)",
    color: "rgba(197, 214, 222, 0.8)",
    background:
      "https://image.tmdb.org/t/p/original/dDdXTkM2mFcIiXbbNjT1paIPYXI.jpg",
    seasons: 3,
    episodes: 24,
    creator: "Robert Kirkman, Simon Racioppa",
    synopsis: "",
    seasons_data: [
      {
        id_serie: 5,
        season_number: 1,
        year: 2021,
        poster: "/series/invincible/INVINCIBLE (2021) - Season 1.png",
        color: "rgba(239, 222, 32, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
        ],
      },
      {
        id_serie: 5,
        season_number: 2,
        year: 2023,
        poster: "/series/invincible/INVINCIBLE (2021) - Season 2.png",
        color: "rgba(147, 56, 35, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
        ],
      },
      {
        id_serie: 5,
        season_number: 3,
        year: 2024,
        poster: "/series/invincible/INVINCIBLE (2021) - Season 3.png",
        color: "rgba(255, 255, 255, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
        ],
      },
    ],
  },
  {
    id: 6,
    type: "serie",
    title: "Gravity Falls",
    group: "animation",
    poster: "/series/gravity_falls/Gravity Falls (2012).jpg",
    color: "rgba(134, 142, 100, 0.8)",
    background:
      "https://image.tmdb.org/t/p/original/lhg7eA6CTOCL10QNVdKiyxkgPsL.jpg",
    seasons: 2,
    episodes: 40,
    creator: "Alex Hirsch",
    synopsis:
      "Dos gemelos pasan el verano con su tío en un misterioso pueblo lleno de criaturas sobrenaturales.",
    seasons_data: [
      {
        id_serie: 6,
        season_number: 1,
        year: 2012,
        poster: "/series/gravity_falls/Gravity Falls (2012) - Season 1.jpg",
        color: "rgba(134, 142, 100, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
          { number: 11, progress: 0 },
          { number: 12, progress: 0 },
          { number: 13, progress: 0 },
          { number: 14, progress: 0 },
          { number: 15, progress: 0 },
          { number: 16, progress: 0 },
          { number: 17, progress: 0 },
          { number: 18, progress: 0 },
          { number: 19, progress: 0 },
          { number: 20, progress: 0 },
        ],
      },
      {
        id_serie: 6,
        season_number: 2,
        year: 2014,
        poster: "/series/gravity_falls/Gravity Falls (2012) - Season 2.jpg",
        color: "rgba(101, 82, 46, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
          { number: 11, progress: 0 },
          { number: 12, progress: 0 },
          { number: 13, progress: 0 },
          { number: 14, progress: 0 },
          { number: 15, progress: 0 },
          { number: 16, progress: 0 },
          { number: 17, progress: 0 },
          { number: 18, progress: 0 },
          { number: 19, progress: 0 },
          { number: 20, progress: 0 },
        ],
      },
    ],
  },
  {
    id: 7,
    type: "serie",
    title: "El Eternauta",
    poster:
      "https://image.tmdb.org/t/p/original/9Krv5NvKa5a3Q3b1l2B3rP9Bj8E.jpg",
    color: "rgba(40, 145, 173, 0.8)",
    background:
      // "https://image.tmdb.org/t/p/original/yMjGzK7L4gwzpQNNtFKDeG79upo.jpg",
      "https://image.tmdb.org/t/p/original/ps7deeE4Ztdp6c0SsMn6v2NyMy4.jpg",
    seasons: 1,
    episodes: 6,
    creator: "Bruno Stagnaro",
    synopsis:
      "Una noche de verano en Buenos Aires, una misteriosa nevada mortal acaba con la mayor parte de la población y deja aisladas a miles de personas.",
    seasons_data: [
      {
        id_serie: 7,
        season_number: 1,
        year: 2023,
        poster: "/series/el_eternauta/The Eternaut (2025) - Season 1.jpg",
        color: "rgba(212, 234, 240, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
        ],
      },
    ],
  },
  {
    id: 8,
    type: "serie",
    title: "Silo",
    poster:
      "https://image.tmdb.org/t/p/original/xcCCQKnJqxkjDoDSMz4LmbKhCRP.jpg",
    color: "rgba(188, 160, 93, 0.8)",
    background:
      "https://image.tmdb.org/t/p/original/eoBKY7sLXChxCPFxYcbxrnr08GO.jpg",
    // "https://image.tmdb.org/t/p/original/b9cuxMdeC1FgEAGvyfzdMJGBMpy.jpg",
    seasons: 2,
    episodes: 20,
    creator: "Graham Yost",
    synopsis:
      "En un mundo subterráneo, los habitantes de un silo luchan por descubrir la verdad detrás de su existencia.",
    seasons_data: [
      {
        id_serie: 8,
        season_number: 1,
        year: 2023,
        poster: "/series/silo/Silo (2023) - Season 1.jpg",
        color: "rgba(236, 148, 53, 0.98)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
        ],
      },
      {
        id_serie: 8,
        season_number: 2,
        year: 2024,
        poster: "/series/silo/Silo (2023) - Season 2.jpg",
        color: "rgba(100, 142, 167, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
        ],
      },
    ],
  },
  {
    id: 9,
    type: "serie",
    title: "El Juego del Calamar",
    poster: "/series/juego_del_calamar/Squid Game (2021).jpg",
    color: "rgba(224, 139, 69, 0.8)",
    background:
      "https://image.tmdb.org/t/p/original/kYd5XcqkoepnZ7MJjtIicfcdTlJ.jpg",
    seasons: 1,
    episodes: 9,
    creator: "Hwang Dong-hyuk",
    synopsis:
      "Un grupo de personas con problemas financieros acepta una misteriosa invitación para participar en un juego mortal.",
    seasons_data: [
      {
        id_serie: 9,
        season_number: 1,
        year: 2021,
        poster: "/series/juego_del_calamar/Squid Game (2021) - Season 1.png",
        color: "rgba(234, 202, 43, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
        ],
      },
      {
        id_serie: 9,
        season_number: 2,
        year: 2024,
        poster: "/series/juego_del_calamar/Squid Game (2021) - Season 2.png",
        color: "rgba(181, 69, 32, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
        ],
      },
      {
        id_serie: 9,
        season_number: 3,
        year: 2025,
        poster: "/series/juego_del_calamar/Squid Game (2021) - Season 3.png",
        color: "rgba(50, 100, 150, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
        ],
      },
    ],
  },
  {
    id: 10,
    type: "serie",
    title: "Rick and Morty",
    group: "animation",
    genre: "comedy",
    poster: "/series/Rick Y Morty/Rick and Morty (2013).jpeg",
    color: "rgba(163, 216, 66, 0.8)",
    background:
      "https://image.tmdb.org/t/p/original/9In9QgVJx7PlFOAgVHCKKSbo605.jpg",
    seasons: 8,
    episodes: 80,
    creator: "Justin Roiland, Dan Harmon",
    synopsis:
      "Un científico loco y su nieto viajan a través de dimensiones y realidades paralelas.",
    seasons_data: [
      {
        id_serie: 10,
        season_number: 1,
        year: 2013,
        poster: "/series/Rick Y Morty/Rick and Morty (2013) - Season 1.jpg",
        color: "rgba(163, 216, 66, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
          { number: 11, progress: 0 },
        ],
      },
      {
        id_serie: 10,
        season_number: 2,
        year: 2015,
        poster: "/series/Rick Y Morty/Rick and Morty (2013) - Season 2.jpg",
        color: "rgba(100, 150, 200, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
        ],
      },
      {
        id_serie: 10,
        season_number: 3,
        year: 2017,
        poster: "/series/Rick Y Morty/Rick and Morty (2013) - Season 3.jpg",
        color: "rgba(200, 100, 150, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
        ],
      },
      {
        id_serie: 10,
        season_number: 4,
        year: 2020,
        poster: "/series/Rick Y Morty/Rick and Morty (2013) - Season 4.jpg",
        color: "rgba(150, 200, 100, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
        ],
      },
      {
        id_serie: 10,
        season_number: 5,
        year: 2021,
        poster: "/series/Rick Y Morty/Rick and Morty (2013) - Season 5.jpg",
        color: "rgba(255, 100, 100, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
        ],
      },
      {
        id_serie: 10,
        season_number: 6,
        year: 2022,
        poster: "/series/Rick Y Morty/Rick and Morty (2013) - Season 6.jpg",
        color: "rgba(100, 255, 100, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
        ],
      },
      {
        id_serie: 10,
        season_number: 7,
        year: 2023,
        poster: "/series/Rick Y Morty/Rick and Morty (2013) - Season 7.jpg",
        color: "rgba(100, 100, 255, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
        ],
      },
      {
        id_serie: 10,
        season_number: 8,
        year: 2024,
        poster: "/series/Rick Y Morty/Rick and Morty (2013) - Season 8.jpg",
        color: "rgba(255, 255, 100, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
        ],
      },
    ],
  },
  {
    id: 11,
    type: "serie",
    title: "Stranger Things",
    poster: "/series/stranger_things/Stranger Things (2016).jpg",
    color: "rgba(227, 33, 33, 0.8)",
    background:
      "https://image.tmdb.org/t/p/original/ihBfoad7sOdPrlMRXmAr3YqQkzW.jpg",
    seasons: 5,
    episodes: 34,
    creator: "The Duffer Brothers",
    synopsis:
      "Un grupo de niños investiga la desaparición de su amigo y descubre un mundo paralelo lleno de criaturas sobrenaturales.",
    seasons_data: [
      {
        id_serie: 11,
        season_number: 1,
        year: 2016,
        poster: "/series/stranger_things/Stranger Things (2016) - Season 1.png",
        color: "rgba(255, 255, 255, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
        ],
      },
      {
        id_serie: 11,
        season_number: 2,
        year: 2017,
        poster: "/series/stranger_things/Stranger Things (2016) - Season 2.png",
        color: "rgba(255, 255, 255, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
        ],
      },
      {
        id_serie: 11,
        season_number: 3,
        year: 2019,
        poster: "/series/stranger_things/Stranger Things (2016) - Season 3.png",
        color: "rgba(255, 255, 255, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
        ],
      },
      {
        id_serie: 11,
        season_number: 4,
        year: 2022,
        poster: "/series/stranger_things/Stranger Things (2016) - Season 4.png",
        color: "rgba(255, 255, 255, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
        ],
      },
      {
        id_serie: 11,
        season_number: 5,
        year: 2024,
        poster: "/series/stranger_things/Stranger Things (2016) - Season 5.png",
        color: "rgba(255, 255, 255, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
        ],
      },
    ],
  },
  {
    id: 12,
    type: "serie",
    title: "Los Simpsons",
    group: "animation",
    poster: "/series/los_simpsons/The Simpsons (1989).jpg",
    color: "rgba(255, 255, 0, 0.8)",
    background:
      "https://image.tmdb.org/t/p/original/3mVaX4kDs3YC96DKnSMOuG9QZQl.jpg",
    seasons: 35,
    episodes: 800,
    creator: "Matt Groening",
    synopsis:
      "La familia Simpson vive en la ciudad ficticia de Springfield y enfrenta diversas situaciones cómicas y satíricas.",
    seasons_data: [],
  },
  {
    id: 13,
    type: "serie",
    title: "Severance",
    poster: "/series/Severance/Severance (2022).jpg",
    color: "rgba(48, 132, 149, 0.8)",
    background:
      "https://image.tmdb.org/t/p/original/r9KaBE7i4ovg8uSppQrCp6ZdPD9.jpg",
    // "https://image.tmdb.org/t/p/original/ixgFmf1X59PUZam2qbAfskx2gQr.jpg",
    seasons: 2,
    episodes: 18,
    creator: "Ben Stiller, Dan Erickson",
    synopsis:
      "Un grupo de empleados de una empresa se somete a un procedimiento de separación para olvidar sus vidas personales.",
    seasons_data: [
      {
        id_serie: 13,
        season_number: 1,
        year: 2022,
        poster: "/series/Severance/Severance (2022) - Season 1.jpg",
        color: "rgba(90, 120, 90, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
        ],
      },
      {
        id_serie: 13,
        season_number: 2,
        year: 2023,
        poster: "/series/Severance/Severance (2022) - Season 2.jpg",
        color: "rgba(75, 123, 160, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
        ],
      },
    ],
  },
  {
    id: 14,
    type: "serie",
    title: "Andor",
    poster: "/series/Andor/Andor (2022).jpg",
    color: "rgba(200, 120, 50, 0.8)",
    background:
      "https://image.tmdb.org/t/p/original/3hPKf2eriMi6B2L5brfQH0A7MNe.jpg",
    seasons: 2,
    episodes: 24,
    creator: "Tony Gilroy",
    synopsis:
      "Un exiliado de la República se convierte en un héroe de la Rebelión.",
    seasons_data: [
      {
        id_serie: 14,
        season_number: 1,
        year: 2022,
        poster: "/series/Andor/Andor (2022) - Season 1.png",
        color: "rgba(111, 117, 131, 1)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
          { number: 11, progress: 0 },
          { number: 12, progress: 0 },
        ],
      },
      {
        id_serie: 14,
        season_number: 2,
        year: 2024,
        poster: "/series/Andor/Andor (2022) - Season 2.png",
        color: "rgba(130, 90, 70, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
          { number: 11, progress: 0 },
          { number: 12, progress: 0 },
        ],
      },
    ],
  },
  {
    id: 15,
    type: "serie",
    title: "The Bear",
    poster: "/series/the_bear/The Bear (2022).png",
    color: "rgba(152, 201, 202, 0.8)",
    background:
      "https://image.tmdb.org/t/p/original/yWoNv7EzrrUSi9cnd9oM2Zo3PEH.jpg",
    seasons: 4,
    episodes: 40,
    creator: "Christopher Storer",
    synopsis:
      "Un chef de cocina regresa a su ciudad natal para dirigir el restaurante familiar luego de la muerte de su hermano.",
    seasons_data: [
      {
        id_serie: 15,
        season_number: 1,
        year: 2022,
        poster: "/series/the_bear/The Bear (2022) - Season 1.png",
        color: "rgba(255, 255, 255, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
        ],
      },
      {
        id_serie: 15,
        season_number: 2,
        year: 2023,
        poster: "/series/the_bear/The Bear (2022) - Season 2.png",
        color: "rgba(255, 255, 255, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
        ],
      },
      {
        id_serie: 15,
        season_number: 3,
        year: 2024,
        poster: "/series/the_bear/The Bear (2022) - Season 3.png",
        color: "rgba(255, 255, 255, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
        ],
      },
      {
        id_serie: 15,
        season_number: 4,
        year: 2025,
        poster: "/series/the_bear/The Bear (2022) - Season 4.png",
        color: "rgba(255, 255, 255, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
          { number: 11, progress: 0 },
          { number: 12, progress: 0 },
        ],
      },
    ],
  },
  {
    id: 16,
    type: "serie",
    title: "Avatar: La Leyenda de Aang",
    group: "animation",
    genre: "fantasy",
    poster: "/series/avatar_animada/Avatar- The Last Airbender (2005) (4).png",
    color: "rgba(15, 95, 156, 0.8)",
    background:
      // "https://image.tmdb.org/t/p/original/fcAxoZhpddnoOtSd0VOKRj80m9m.jpg",
      "https://image.tmdb.org/t/p/original/nLKYAJCEi6OQVji1HJIxSQ74H9s.jpg",
    seasons: 3,
    episodes: 61,
    creator: "Michael Dante DiMartino, Bryan Konietzko",
    synopsis:
      "En un mundo donde los elementos son controlados por maestros, un joven llamado Aang debe aprender a dominar los cuatro elementos para restaurar la paz.",
    seasons_data: [
      {
        id_serie: 16,
        season_number: 1,
        year: 2005,
        poster:
          "/series/avatar_animada/Avatar- The Last Airbender (2005) - Season 1 (1).png",
        color: "rgba(85, 170, 225, 0.8)",
        episodes: [
          { number: 1, progress: 100 },
          { number: 2, progress: 100 },
          { number: 3, progress: 100 },
          { number: 4, progress: 100 },
          { number: 5, progress: 100 },
          { number: 6, progress: 100 },
          { number: 7, progress: 100 },
          { number: 8, progress: 100 },
          { number: 9, progress: 100 },
          { number: 10, progress: 100 },
          { number: 11, progress: 100 },
          { number: 12, progress: 100 },
          { number: 13, progress: 100 },
          { number: 14, progress: 100 },
          { number: 15, progress: 0 },
          { number: 16, progress: 0 },
          { number: 17, progress: 0 },
          { number: 18, progress: 0 },
          { number: 19, progress: 0 },
          { number: 20, progress: 0 },
        ],
      },
      {
        id_serie: 16,
        season_number: 2,
        year: 2006,
        poster:
          "/series/avatar_animada/Avatar- The Last Airbender (2005) - Season 2 (1).png",
        color: "rgba(103, 194, 115, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
          { number: 11, progress: 0 },
          { number: 12, progress: 0 },
          { number: 13, progress: 0 },
          { number: 14, progress: 0 },
          { number: 15, progress: 0 },
          { number: 16, progress: 0 },
          { number: 17, progress: 0 },
          { number: 18, progress: 0 },
          { number: 19, progress: 0 },
          { number: 20, progress: 0 },
        ],
      },
      {
        id_serie: 16,
        season_number: 3,
        year: 2007,
        poster:
          "/series/avatar_animada/Avatar- The Last Airbender (2005) - Season 3 (1).png",
        color: "rgba(237, 104, 63, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
          { number: 11, progress: 0 },
          { number: 12, progress: 0 },
          { number: 13, progress: 0 },
          { number: 14, progress: 0 },
          { number: 15, progress: 0 },
          { number: 16, progress: 0 },
          { number: 17, progress: 0 },
          { number: 18, progress: 0 },
          { number: 19, progress: 0 },
          { number: 20, progress: 0 },
          { number: 21, progress: 0 },
        ],
      },
    ],
  },
  {
    id: 17,
    type: "serie",
    title: "Loki",
    genre: "superheroes",
    poster: "/series/loki/Loki (2021).jpg",
    color: "rgba(117, 180, 69, 0.8)",
    background:
      "https://image.tmdb.org/t/p/original/uFur8XI3OlL0OtelM7wLUgRiIS2.jpg",
    seasons: 2,
    episodes: 12,
    creator: "Michael Waldron",
    synopsis:
      "Después de los eventos de 'Avengers: Endgame', Loki se encuentra en una nueva línea temporal y debe enfrentarse a la Autoridad de Variación Temporal.",
    seasons_data: [
      {
        id_serie: 17,
        season_number: 1,
        year: 2021,
        poster: "/series/loki/Loki (2021) - Season 1.png",
        color: "rgba(244, 158, 30, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
        ],
      },
      {
        id_serie: 17,
        season_number: 2,
        year: 2023,
        poster: "/series/loki/Loki (2021) - Season 2.png",
        color: "rgba(155, 122, 92, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
        ],
      },
    ],
  },
  {
    id: 18,
    type: "serie",
    title: "Arcane",
    genre: "action",
    group: "animation",
    poster: "/series/arcane/Arcane (2021).png",
    color: "rgba(255, 87, 129, 0.8)",
    background: "https://wallpapercave.com/wp/wp10932037.jpg",
    seasons: 1,
    episodes: 9,
    creator: "Christian Linke, Alex Yee",
    synopsis:
      "En la ciudad de Piltover, dos hermanas se ven envueltas en un conflicto entre la magia y la tecnología.",
    seasons_data: [
      {
        id_serie: 18,
        season_number: 1,
        year: 2021,
        poster: "/series/arcane/Arcane (2021) - Season 1.png",
        color: "rgba(224, 186, 80, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
        ],
      },
      {
        id_serie: 18,
        season_number: 2,
        year: 2024,
        poster: "/series/arcane/Arcane (2021) - Season 2.png",
        color: "rgba(74, 228, 54, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
        ],
      },
    ],
  },
  {
    id: 19,
    type: "serie",
    title: "Samurai de Ojos Azules",
    group: "animation",
    poster: "/series/samurai_azul/BLUE EYE SAMURAI (2023).png",
    color: "rgba(255, 70, 33, 0.8)",
    background:
      "https://wallpaperbat.com/img/1847783-blue-eyed-samurai-hd-wallpaper.jpg",
    seasons: 1,
    episodes: 8,
    creator: "Michael Taylor, Amber Noizumi",
    synopsis:
      "Un samurái mestizo busca venganza en un mundo lleno de traiciones y secretos.",
    seasons_data: [
      {
        id_serie: 19,
        season_number: 1,
        year: 2023,
        poster: "/series/samurai_azul/BLUE EYE SAMURAI (2023) - Season 1.png",
        color: "rgba(0, 0, 0, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
        ],
      },
    ],
  },
  {
    id: 20,
    type: "serie",
    title: "Shogun",
    poster: "/series/shogun/Shogun (2024).png",
    color: "rgba(255, 255, 255, 0.8)",
    background:
      "https://image.tmdb.org/t/p/original/tZcZqfy1HgDZe2Fpnt32AgE8nif.jpg",
    seasons: 1,
    episodes: 8,
    creator: "Justin Doble, Jason Brown",
    synopsis:
      "Un comerciante inglés se convierte en un samurái en el Japón feudal, enfrentándose a intrigas políticas y culturales.",
    seasons_data: [
      {
        id_serie: 20,
        season_number: 1,
        year: 2024,
        poster: "/series/shogun/Shogun (2024) - Season 1.png",
        color: "rgba(255, 255, 255, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
        ],
      },
    ],
  },
  {
    id: 21,
    type: "serie",
    title: "BoJack Horseman",
    group: "animation",
    poster: "/series/bojack_horseman/BoJack Horseman (2014).jpg",
    // poster: "https://image.tmdb.org/t/p/original/pB9L0jAnEQLMKgexqCEocEW8TA.jpg",
    color: "rgba(219, 22, 202, 0.8)",
    background:
      "https://image.tmdb.org/t/p/original/5tIZcCjh0HmxMUYJz0FiVabNttP.jpg",
    seasons: 6,
    episodes: 77,
    creator: "Raphael Bob-Waksberg",
    synopsis:
      "La vida de un actor fracasado que intenta encontrar su camino en el mundo.",
    seasons_data: [
      {
        id_serie: 21,
        season_number: 1,
        year: 2014,
        poster:
          "/series/bojack_horseman/BoJack Horseman (2014) - Season 1.jpeg",
        color: "rgba(255, 255, 255, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
          { number: 11, progress: 0 },
          { number: 12, progress: 0 },
        ],
      },
      {
        id_serie: 21,
        season_number: 2,
        year: 2015,
        poster:
          "/series/bojack_horseman/BoJack Horseman (2014) - Season 2.jpeg",
        color: "rgba(255, 255, 255, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
          { number: 11, progress: 0 },
          { number: 12, progress: 0 },
        ],
      },
      {
        id_serie: 21,
        season_number: 3,
        year: 2016,
        poster: "/series/bojack_horseman/BoJack Horseman (2014) - Season 3.jpg",
        color: "rgba(255, 255, 255, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
          { number: 11, progress: 0 },
          { number: 12, progress: 0 },
        ],
      },
      {
        id_serie: 21,
        season_number: 4,
        year: 2017,
        poster: "/series/bojack_horseman/BoJack Horseman (2014) - Season 4.jpg",
        color: "rgba(255, 255, 255, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
          { number: 11, progress: 0 },
          { number: 12, progress: 0 },
        ],
      },
      {
        id_serie: 21,
        season_number: 5,
        year: 2018,
        poster:
          "/series/bojack_horseman/BoJack Horseman (2014) - Season 5.jpeg",
        color: "rgba(255, 255, 255, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
          { number: 11, progress: 0 },
          { number: 12, progress: 0 },
        ],
      },
      {
        id_serie: 21,
        season_number: 6,
        year: 2020,
        poster:
          "/series/bojack_horseman/BoJack Horseman (2014) - Season 6.jpeg",
        color: "rgba(255, 255, 255, 0.8)",
        episodes: [
          { number: 1, progress: 0 },
          { number: 2, progress: 0 },
          { number: 3, progress: 0 },
          { number: 4, progress: 0 },
          { number: 5, progress: 0 },
          { number: 6, progress: 0 },
          { number: 7, progress: 0 },
          { number: 8, progress: 0 },
          { number: 9, progress: 0 },
          { number: 10, progress: 0 },
          { number: 11, progress: 0 },
          { number: 12, progress: 0 },
          { number: 13, progress: 0 },
          { number: 14, progress: 0 },
          { number: 15, progress: 0 },
          { number: 16, progress: 0 },
        ],
      },
    ],
  },
];
